# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
	const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
	const response = await fetch(url);
	const users = await response.json();
	console.log(users);
	return users;
};
getUser(-1);
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer

I don't think that function is safe. Because on like 8, after the `fetch` has been complete, there is no chaining to identify if the response is sucessful. There is no `try` `catch` that is set up in order to have a guard function if the `response.ok` is `false`.

# Teacher Feedback
